
[package]
name = "ripgrep_all"
description = "rga: ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz, etc."
license = "AGPL-3.0-or-later"
readme = "README.md"
version = "0.9.7-alpha.0"
repository = "https://github.com/phiresky/ripgrep-all"
homepage = "https://github.com/phiresky/ripgrep-all"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"
exclude = [
    "exampledir/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree_magic = { package = "tree_magic_mini", version = "1.0.0" }
regex = "1.3.9"
rkv = "0.10.4"
path-clean = "0.1.0"
bincode = "1.3.1"
serde = { version = "1.0.115", features = ["derive"] }
zstd = "0.5.3"
lazy_static = "1.4.0"
serde_json = "1.0.57"
zip = {path="../zip-rs"}
crossbeam = "0.7.3"
clap = { version = "2.33.3", features = ["wrap_help"] }
log = "0.4.11"
env_logger = "0.7.1"
xz2 = "0.1.6"
flate2 = "1.0.14"
bzip2 = "0.4.1"
tar = "0.4.30"
chrono = "0.4.15"
encoding_rs = "0.8.24"
encoding_rs_io = "0.1.7"
rusqlite = { version = "0.24.0", features = ["vtab", "bundled"] }
size_format = "1.0.2"
structopt = "0.3.17"
paste = "1.0.0"
tempfile = "3.1.0"
glob = "0.3.0"
anyhow = "1.0.32"
schemars = { version = "0.8.0-alpha-4", features = ["preserve_order"] }
directories-next = "1.0.1"
derive_more = "0.99.9"
pretty-bytes = "0.2.2"
memchr = "2.3.3"
crossbeam-channel = "0.4.4"
dyn-clone = "1.0.2"
dyn-clonable = "0.9.0"
